### ISSUE TITLE
fix(4.2): update patch for Spring4shell vulnerability

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-oxshibboleth#50]
This is targeting a patch for gluu `4.2.3` version
The configuration files are here : `https://jenkins.gluu.org/maven/org/gluu/oxShibbolethStatic/4.2.3.Final/oxShibbolethStatic-4.2.3.Final.jar`

The war to use : `https://jenkins.gluu.org/maven/org/gluu/oxshibbolethIdp/4.2.3.Final/oxshibbolethIdp-4.2.3.Final.war`

There’s an additional step to have it running though

You may need to generate the files `/opt/shibboleth-idp/credentials/sealer.jks` and `/opt/shibboleth-idp/credentials/sealer.ver` if they are not already generated but for `4.2.3` we did not have those.

##### CE related commands:

create directory dist in `/opt/shibboleth-idp/`

Then copy the `/opt/shibboleth-idp/webapp `directory into it , so you obtain the directory /`opt/shibboleth-idp/dist/webapp`

Run the following commands:

```
export JAVA_HOME=/opt/jre
export PATH=$JAVA_HOME/bin:$PATH
export IDP_HOME=/opt/shibboleth-idp
$IDP_HOME/bin/seckeygen --storefile $IDP_HOME/credentials/sealer.jks --storepass <store password> --versionfile $IDP_HOME/credentials/sealer.kver --alias secret
```
You can set whatever store password you want (first run) , but it needs to be stored in /opt/shibboleth-idp/idp.properties under the key idp.sealer.storePassword

**Comment by iromli** [comment]
The v4.2.3 already have `sealer.jks` and `sealer.ver` inside the image container/pod.

```
/opt/shibboleth-idp/credentials # ls -l
total 8
-rw-r--r--    1 root     root           502 Nov 14 16:13 sealer.jks
-rw-r--r--    1 root     root            47 Nov 14 16:13 sealer.kver
```

> You may need to generate the files /opt/shibboleth-idp/credentials/sealer.jks and /opt/shibboleth-idp/credentials/sealer.ver if they are not already generated but for 4.2.3 we did not have those.

**Comment by iromli** [comment]
Required files has been updated in branch `4.2`.
